---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/preferences.yml
    - include: tasks/dockutil.yml
      when: '"dockutil" in homebrew_installed_packages'
    - include: tasks/sublime.yml
      when: '"sublime-text" in homebrew_cask_apps'

    - name: Run .osx dotfiles.
      shell: ~/.osx --no-restart
      changed_when: false
      when: '".osx" in dotfiles_files'