---
- name: geerlingguy.dotfiles
- name: geerlingguy.homebrew
#  src: https://github.com/tschifftner/ansible-role-homebrew
#- name: fubarhouse.sublime-drupal
- name: fubarhouse.macdock
- name: fubarhouse.macfonts
- name: fubarhouse.macstore