---

- name: Sublime | Ensure sublime directories exists.
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ {{ sublime_dir }} }}"
    - "{{ sublime_dir }}/{{ sublime_packageman_dir }}"
    - "{{ sublime_dir }}/{{ sublime_packages_dir }}"

- name: Sublime | Copying configuration
  copy:
    src: "./files/sublime/Library/Packages/User/Preferences.sublime-settings"
    dest: "{{ sublime_dir }}/{{ sublime_packages_dir }}/User/Preferences.sublime-settings"

- name: Sublime | Install Package Manager
  get_url:
    url: "https://packagecontrol.io/Package%20Control.sublime-package"
    dest: "{{ sublime_dir }}/{{ sublime_packageman_dir }}/Package Control.sublime-package"

- name: Sublime | Install Packages
  git:
    repo: "{{ item.repo }}"
    dest: "{{ sublime_dir }}/{{ sublime_packages_dir }}/{{ item.name }}"
    clone: yes
    update: yes
    force: yes
    accept_hostkey: yes
  become: no
  with_items: "{{ sublime_packages }}"
